---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    nginx_vts_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- name: Check if nginx_vts_exporter is installed
  stat:
    path: "/usr/local/bin/nginx-vts-exporter"
  register: __nginx_vts_exporter_is_installed
  tags:
    - nginx_vts_exporter_install

- name: Gather currently installed nginx_vts_exporter version (if any)
  command: "/usr/local/bin/nginx-vts-exporter --version"
  args:
    warn: false
  changed_when: false
  register: __nginx_vts_exporter_current_version_output
  when: __nginx_vts_exporter_is_installed.stat.exists
  tags:
    - nginx_vts_exporter_install
    - skip_ansible_lint
